### ISSUE TITLE
Consider widening `gleam_json` constraint to include >= 1.0.0

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [violetbuse/httpp#1]
the `gleam_json` api is stable and didn't change between v1 and v2. Instead, the v2 release dropped the dependency on thoas and uses OTP 27's built-in json handling.

Not everyone will have OTP 27, including mac users using brew. It'd be great if we could widen the constraint so more folks can use this package :)

**Comment by violetbuse** [comment]
yeah I'll add it later today

**Comment by violetbuse** [comment]
I have removed the dependency on gleam_json entirely. hope this helps <3
